export const SELECT_STATEMENT = "SELECT_STATEMENT";
export const UPDATE_STATEMENT = "UPDATE_STATEMENT";
export const INSERT_STATEMENT = "INSERT_STATEMENT";
export const DELETE_STATEMENT = "DELETE_STATEMENT";
export const FIRESTATION_DATA_PROP = "FIRESTATION_DATA_PROP";
export const NO_EQUALITY_STATEMENTS = "NO_EQUALITY_STATEMENTS";
export const EQUATION_IDENTIFIERS = [" / ", " + ", " - ", " * "];
